# Generated by Django 2.1.5 on 2023-03-09 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('admin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_pw', models.CharField(max_length=255)),
                ('admin_age', models.IntegerField(blank=True, null=True)),
                ('admin_email', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_telephone', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'administrator',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('manager_pw', models.CharField(max_length=255)),
                ('manager_age', models.IntegerField(blank=True, null=True)),
                ('manager_email', models.CharField(blank=True, max_length=255, null=True)),
                ('manager_telephone', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'manager',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_price', models.FloatField(blank=True, null=True)),
                ('selling_price', models.FloatField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('warehouse_id', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Product')),
            ],
            options={
                'db_table': 'record',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Administrator')),
            ],
            options={
                'db_table': 'warehouse',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Warehouse'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='manager_name',
            field=models.ForeignKey(db_column='manager_name', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Manager'),
        ),
    ]
