# Generated by Django 2.1.5 on 2023-03-09 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='default.jpg', upload_to='profile_images')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.Administrator')),
            ],
        ),
    ]
